
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Menu from "../components/Menu";
import Hero from "../components/Hero";
import ThreeColumns from "../components/ThreeColumns";
import Goals from "../components/Goals";
import About from "../components/About";
import Foundation from "../components/Foundation";
import React from "react";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


            <main className={styles.main}>
              <Menu></Menu>
              <div id="start">
                <Hero></Hero>
              </div>
              <ThreeColumns></ThreeColumns>
              <div id="goal">
                <Goals></Goals>
              </div>
              <div id="about">
                <About></About>
              </div>
              <div id="fundations">
                <Foundation></Foundation>
              </div>
              <div id="contact">
                <Contact></Contact>
              </div>





            </main>
    </div>
  )
}
